
services:
  server:
    build: .
    ports:
      - "2567:2567"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27018/chat
      - JWT_SECRET=your_jwt_secret
    networks:
      - chat_network

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge
